name: Create Pyrogram Session

on:
  workflow_dispatch:

jobs:
  create-session:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyrogram tgcrypto

      - name: Run Pyrogram session creation
        run: |
          python create_session.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
