name: Create Pyrogram Session

on: workflow_dispatch

jobs:
  create-session:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Setting up job"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyrogram tgcrypto

      - name: Run Pyrogram session creation
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: python create_session.py

      - name: Compress session file
        run: tar -czvf session.tar.gz session.txt

      - name: Display download link
        run: echo "Session file is ready. You can download it from the artifacts tab."
